name: GitHub Actions

on:
  push:
    branches: ['main','master']
  pull_request:
    branches: ['main','master']
  schedule:
    # run once a month (until 60 days of repo inactivity hits)
    #  (time in UTC, run at 7:45 EST depending on daylight savings)
    - cron: '45 11 16 * *'

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Link Checker (lychee)
      id: lychee
      uses: lycheeverse/lychee-action@v2
      # certain links are excluded from checking via .lycheeignore
